select * from customer

--Q1. Which customers used a discount but still spent more than average purchase
select customer_id,purchase_amount
from customer
where subscription_status ='Yes' and purchase_amount >=(select avg(purchase_amount) from customer);

--Q2.What is revenue generated by male vs.female customers?
select gender,sum(purchase_amount) as revenue
from customer
group by gender;

--Q3.Which are top 5 products with the highest average review ratings
select item_purchased,ROUND(avg(review_rating::numeric),2) as avg_review
from customer
group by item_purchased
order by avg_review desc
limit 5;

--Q4.Compare the average Purchase Amount between Standard and express shipping.
select shipping_type,round(avg(purchase_amount),2) as avg_purchase
from customer
where shipping_type in ('Express','Standard')
group by shipping_type;

--Q5.Do subscribed customer spend more? compare average spend and total revenue between subscribers and non subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6.Which 5 products have the highest percentage of purchase with discounts applied?
select item_purchased,
round(100.0*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_percentage
from customer
group by item_purchased
order by discount_percentage desc 
limit 5;


--Q7.Segement the customers into new, Returning,the loyal based on their total
--number of previous purchases, and show the count of each segement.

with customer_type as (
select customer_id,previous_purchases,
case 
	when previous_purchases =1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segement
from customer
)

select customer_segement,count(*) as number_of_customer
from customer_type
group by customer_segement;

--Q8.What are the top 3 most purchased product within each category?
with item_counts as (
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category ,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

--Q9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;

--Q10.What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_purchase
from customer
group by age_group
order by total_purchase desc;